### ISSUE TITLE
Do not hard code unit numbers in a subroutine

### ISSUE THREAD

**Issue by Beliavsky** [chowland/AFiD-MuRPhFi#44]
In the subroutine at https://github.com/chowland/AFiD-MuRPhFi/blob/main/src/CalcWriteQ.F90

the unit number 45 is used. This makes the program less safe and extensible, because it is possible that the unit number could already be in use elsewhere in the program. It's better to use the `newunit` feature of Fortran 2008 to get a free unit number, as described at https://www.ibm.com/docs/en/xffbg/121.141?topic=attributes-open .

**Comment by chowland** [comment]
Thanks for taking a look at the code @Beliavsky. You make a good point about unit numbers for I/O. I have been using `newunit` in the recent additions I have made (such as in the `moisture` or `phasefield` modules) but there seem to be a lot of unsafe usages in the legacy parts of the code. I'll make a PR to tidy these up
